### ISSUE TITLE
Command will not work

### ISSUE THREAD

**Issue by emillal** [danishgufran/tensorflow-2.X-for-Xilinx-Pynq-Z2#1]
$ wget https://github.com/danishgufran/tensorflow-2.X-for-Xilinx-Pynq-Z2/blob/main/Tensorflow%202.1%20wheel%20file 

this command will not directly work as it is not able to download from a drive.

**Comment by danishgufran** [comment]
Try this : https://drive.google.com/file/d/1nZyPO1s6i3es7-ApkLB9k97p4v62CVPV/view?usp=sharing

**Comment by emillal** [comment]
I used the file and followed through with the installation,but when i tried running it i had the following error. 
I am using the same configuration PYNQ Z2 with v2.6 image. Was this error coming for you also. If so, how did you rectify it?
I would really appreciate it,if you could help me out.Thanks.

xilinx@pynq:~$ python3 --version
Python 3.6.5
xilinx@pynq:~$ python3
Python 3.6.5 (default, Apr  1 2018, 05:46:30)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/__init__.py", line 50, in <module>
    from tensorflow.python import _pywrap_utils
ImportError: /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/_pywrap_utils.so: undefined symbol: PyThread_tss_alloc

**Comment by saikiranreddypv2104** [comment]
I'm having the same issue. Did you find any solution??, Is there any work around.
