### ISSUE TITLE
Error while importing tensorflow

### ISSUE THREAD

**Issue by saikiranreddypv2104** [danishgufran/tensorflow-2.X-for-Xilinx-Pynq-Z2#2]
I followed the steps. The TensorFlow is installed successfully, but I'm getting this error while importing the the TensorFlow.

```
 import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/__init__.py", line 50, in <module>
    from tensorflow.python import _pywrap_utils
ImportError: /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/_pywrap_utils.so: undefined symbol: PyThrea
d_tss_alloc
```

**Comment by danishgufran** [comment]
Looks like you have a different Python version installed. The whl file uses python 3.6.0.

**Comment by saikiranreddypv2104** [comment]
I'm using Python 3.6.5

```python
root@pynq:/home/xilinx# python --version
Python 3.6.5
```
is there any work round?
